name: Update README Alternating Time

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecutará todos los días a la medianoche (UTC)
  workflow_dispatch:  # También permite ejecutarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Actualizar a v3

      - name: Set up Python
        uses: actions/setup-python@v3  # Actualizar a v3
        with:
          python-version: '3.x'

      - name: Run the script to update README
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Auto-update README with alternating time"
          git push
